# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Dashboard
background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
theme: dark
color: slate

layout:
  "Services":
    style: row
  "Infrastructure":
    style: row
  "Monitoring":
    style: row

providers:
  openweathermap: ${OPENWEATHERMAP_API_KEY}
  weatherapi: ${WEATHERAPI_API_KEY}
